---
- hosts: all
  tasks:
    - name: Disable all repositories
      command: "/usr/bin/subscription-manager repos --disable=*"
    - name: Enable specified repositories
      command: "/usr/bin/subscription-manager repos --enable={{ item }}"
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-optional-rpms
    - name: Check yum repolist
      command: "yum repolist enabled"
      args:
        warn: no
      register: result
    - name: Print result
      debug:
        msg: "{{ result }}"
