---
- hosts: "{{ variable_host | default('all') }}"
  tasks:
    - name: Disable all repositories
      command: "/usr/bin/subscription-manager repos --disable=*"
      ignore_errors: yes

    - name: Setting enabled=0 in subscription-manager.conf
      lineinfile:
        path: /etc/yum/pluginconf.d/subscription-manager.conf
        regexp: '^enabled'
        line: 'enabled=0'

    - name: Add rhel-8-for-x86_64-appstream-rpms mirror repositories
      yum_repository:
        name: mirror-rhel-8-for-x86_64-appstream-rpms
        file: local_mirror
        baseurl: http://bastion.pichuang.local/rhel-8-for-x86_64-appstream-rpms
        description: Local rhel-8-for-x86_64-appstream-rpms
        gpgcheck: no

    - name: Add rhel-8-for-x86_64-baseos-rpms mirror repositories
      yum_repository:
        name: mirror-rhel-8-for-x86_64-baseos-rpms
        file: local_mirror
        baseurl: http://bastion.pichuang.local/rhel-8-for-x86_64-baseos-rpms
        description: Local rhel-8-for-x86_64-baseos-rpms
        gpgcheck: no

    - name: Add ansible-2.9-for-rhel-8-x86_64-rpms mirror repositories
      yum_repository:
        name: mirror-ansible-2.9-for-rhel-8-x86_64-rpms
        file: local_mirror
        baseurl: http://bastion.pichuang.local/ansible-2.9-for-rhel-8-x86_64-rpms
        description: Local ansible-2.9-for-rhel-8-x86_64-rpms
        gpgcheck: no

    - name: Add EPEL repository
      yum_repository:
        name: epel
        state: present
        description: EPEL YUM repo
        baseurl: "https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/"
        gpgcheck: no
        enabled: no

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Check yum repolist
      command: "yum repolist enabled"
      args:
        warn: no
      register: result

    - name: Print result
      debug:
        msg: "{{ result }}"
