---
- hosts: all
  vars:
    username: "{{ username }}"
    password: "{{ password }}"
    pool_ids: "{{ pool_ids }}"

  tasks:
    - name: Register as user with password and auto-subscribe to a specific pool by ID
      redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        pool_ids: "{{ pool_ids }}"
      register: result

    - name: Print message
      debug:
        msg: "{{ result }}"


