---
- hosts: "{{ variable_host | default('all') }}"
  tasks:
    - name: Disable all repositories
      command: "/usr/bin/subscription-manager repos --disable=*"

    - name: Add rhel-7-server-rpms mirror repositories
      yum_repository:
        name: mirror-rhel-7-server-rpms
        file: local_mirror
        baseurl: http://bastion.pichuang.local/rhel-7-server-rpms
        description: Local rhel-7-server-rpms
        gpgcheck: no

    - name: Add rhel-7-server-optional-rpms mirror repositories
      yum_repository:
        name: mirror-rhel-7-server-optional-rpms
        file: local_mirror
        baseurl: http://bastion.pichuang.local/rhel-7-server-optional-rpms
        description: Local rhel-7-server-optional-rpms
        gpgcheck: no

    - name: Add rhel-7-server-extras-rpms mirror repositories
      yum_repository:
        name: mirror-rhel-7-server-extras-rpms
        file: local_mirror
        baseurl: http://bastion.pichuang.local/rhel-7-server-extras-rpms
        description: Local rhel-7-server-extras-rpms
        gpgcheck: no

    - name: Add rhel-7-server-ose-3.9-rpms mirror repositories
      yum_repository:
        name: mirror-rhel-7-server-ose-3.9-rpms
        file: local_mirror
        baseurl: http://bastion.pichuang.local/rhel-7-server-ose-3.9-rpms
        description: Local rhel-7-server-ose-3.9-rpms
        gpgcheck: no

    - name: Add rhel-7-fast-datapath-rpms mirror repositories
      yum_repository:
        name: mirror-rhel-7-fast-datapath-rpms
        file: local_mirror
        baseurl: http://bastion.pichuang.local/rhel-7-fast-datapath-rpms
        description: Local rhel-7-fast-datapath-rpms
        gpgcheck: no

    - name: Add rhel-7-server-3scale-amp-2.2-rpms mirror repositories
      yum_repository:
        name: mirror-rhel-7-server-3scale-amp-2.2-rpms
        file: local_mirror
        baseurl: http://bastion.pichuang.local/rhel-7-server-3scale-amp-2.2-rpms
        description: Local rhel-7-server-3scale-amp-2.2-rpms
        gpgcheck: no


    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Check yum repolist
      command: "yum repolist enabled"
      args:
        warn: no
      register: result

    - name: Print result
      debug:
        msg: "{{ result }}"
